### PR TITLE
Support regex path

### PR DESCRIPTION
**Pull request by daicang**
Hi, we would like our Marathon to have access control with LDAP, and we find this plugin, it works fine! 
However, we need to control access to specific folder, regardless of its parent folder(like `/dev/${app1}/consumer/` and `/dev/${app2}/consumer/`). So with this PR marathon-ldap can work with regex path(then we can give the path `/dev/.*/consumer/`  ; P).

### CODE REVIEW

**Comment by gondor** [comment]
@daicang thank you! I like this idea a lot and it looks good.  My question to you is have we tested backwards compatibility?   What about people who already have the configuration with `/` and not the trailing `.*`.  Will that still match?

**Comment by daicang** [comment]
@gondor As you noticed, currently `/` would not match its subdirectory, so we have to change '/' to '/.*'. I'll fix it ASAP.

**Comment by daicang** [comment]
@gondor 
Now it's backward compatible, no need to write `${dir}/.*`, simply `${dir}` or `${dir}/` would match all subdirectories.

**Comment by gondor** [comment]
Awesome, job!   Merging - will cut a release tonight or tomorrow

**Pull request merged**
